## roles/zsh/tasks/main.yml
## Role main file
# vim:ft=ansible:
---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"
### TODO: Make pip dist variable
- name: Install packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - zsh
    - git
    - '{{ pip_package }}'
  notify:
    - Installscript for oh-my-zsh
    - Run installer

- name: set zsh as shell
  user:
    name: '{{ item.key }}'
    shell: /bin/zsh
    state: 'present'
    createhome: no
  with_dict: '{{ userlist }}'

- meta: flush_handlers

- name: prompt confs
  template:
    src: '{{ item.name }}.j2'
    dest: '{{ item.dest }}/{{ item.name }}'
  with_items:
    - { name: 'aliases.zsh', dest: /etc/zsh/zsh.d/}
    - { name: 'zshrc', dest: /etc/zsh/}
  tags: zshconf

- template:
    src: '.Xresources.j2'
    dest: '{{ item.value }}{{ item.key }}/.Xresources'
  with_dict: '{{ userlist }}'
  ignore_errors: True
  tags: xresources

- copy:
    src: bullet-train.zsh-theme
    dest: /etc/zsh/zsh.d/oh-my-zsh/themes

- name: exa install (RedHat)
  import_tasks: RedHat.yml
  when: "'RedHat' in ansible_os_family"

- name: exa install (Arch Linux)
  yaourt: 
    name: exa-git
    state: present
  become: yes
  become_user: '{{ as_user }}'
  when: "'Arch Linux' in ansible_distribution"

- name: libhttp-parser (debian-based distros)
  package:
    name: libhttp-parser2.1
    state: present
  when: "'Debian' in ansible_os_family"

- name: .zshrc
  template:
    src: .zshrc.j2
    dest: '{{ item.value }}{{ item.key }}/.zshrc'
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
  with_dict: '{{ userlist }}'
  ignore_errors: yes

- name: powerline status
  pip:
    name: powerline-status
    executable: pip3

- name: powerline git
  pip:
    name: powerline-gitstatus
    executable: pip3

- name: "powerline colors"
  template:
    src: 'powerline/config_files/{{ item }}.j2'
    dest: '{{ pline_path }}{{ item }}'
  with_items:
    - 'colors.json'
    - 'colorschemes/default.json'
    - 'colorschemes/shell/default.json'
    - 'themes/shell/default.json'
    - 'themes/shell/__main__.json'
...
